forminst_new1/config/routes.rb
Rails.application.routes.draw do
  resources :documents
	post 'iniciotutor/ver_detalles_plan', to: 'iniciotutor#ver_detalles_plan'
	get 'adecuacions/descargar_pdf', to: 'adecuacions#descargar_pdf'
	get ':controller(/:action(/:id(.:format)))'
	post ':controller(/:action(/:id(.:format)))'
	root 'forminst#index'

  resources :resumes, only: [:index, :new, :create, :destroy]
  root "resumes#index"

end

forminst_new1/app/models/adecuacion.rb
class Adecuacion < ActiveRecord::Base
	belongs_to :usuario
	belongs_to :planformacion
	has_many :estatus_adecuacion
	has_many :revision
	has_many :adecuacion_actividad
end

forminst_new1/app/controllers/adecuacions_controller.rb
class AdecuacionsController < ApplicationController

  def generar_pdf() # es función permite generar el documento pdf de la adecuación
    @adecuacion= Adecuacion.find(session[:adecuacion_id]) # se obtienen la información de la adecuación seleccionada
    @planformacion= Planformacion.find(@adecuacion.planformacion_id)
    @fechaConcurso = @planformacion.fecha_inicio
    @id_docente= @planformacion.tutor_id # se obtiene el indicador del ususario al que corresponde la adecuación
    @usertutor= Usuario.find(@id_docente) # se obtiene la información del tutor mediante la base de datos y la variable anterior
    @tutor= Persona.where(usuario_id: @id_docente).take
    @id_instructor= @planformacion.instructor_id # se toma el identificador del instructor
    @userinst=Usuario.find(@id_instructor) # se obtienen toda la información del instructor 
    @instructor= Persona.where(usuario_id: @id_instructor).take
    @fechaActual = Date.current.to_s
    @userentidad= Usuarioentidad.where(usuario_id: @planformacion.instructor_id).take
      if @userentidad.escuela_id == nil
        @userentidad.escuela_id=12
        @userentidad.save
        @escuela= Escuela.where(id: @userentidad.escuela_id).take
      else
        @escuela= Escuela.where(id: @userentidad.escuela_id).take
      end

    @userinst2=Usuario.find(@id_docente) # se obtienen toda la información del tutor
    @correot= @userinst2.user+'@ciens.ucv.ve'
    @correoi=  @userinst.user+'@ciens.ucv.ve'
    
    @pactv_docencia= []
    @pactv_investigacion= []
    @pactv_formacion= []
    @pactv_extension=[]
    @pactv_otras=[]
    @sactv_docencia= []
    @sactv_investigacion= []
    @sactv_formacion= []
    @sactv_extension=[]
    @sactv_otras=[]
    @tactv_docencia= []
    @tactv_investigacion= []
    @tactv_formacion= []
    @tactv_extension=[]
    @tactv_otras=[]
    @cactv_docencia= []
    @cactv_investigacion= []
    @cactv_formacion= []
    @cactv_extension=[]
    @cactv_otras=[]
    @dactv_docencia= []
    @dactv_investigacion= []
    @dactv_formacion= []
    @dactv_extension=[]

    @actividadesa= AdecuacionActividad.where(adecuacion_id: @adecuacion.id, semestre: 1).all
    @actividadesa.each do |actade| 
      @act= Actividad.find(actade.actividad_id)
      tipo= @act.tipo_actividad_id
      if tipo==1
        @pactv_docencia.push(@act)
      else
        if tipo==2
          @pactv_investigacion.push(@act)
        else
          if tipo==3
            @pactv_extension.push(@act)
          else
            if tipo==4
              @pactv_formacion.push(@act)
            else
              if tipo==5
                @pactv_otras.push(@act)
              end
            end
          end
        end
      end
    end

    @sactividadesa= AdecuacionActividad.where(adecuacion_id: @adecuacion.id, semestre: 2).all
    @sactividadesa.each do |actade| 
      @act= Actividad.find(actade.actividad_id)
      tipo= @act.tipo_actividad_id
      if tipo==1
        @sactv_docencia.push(@act)
      else
        if tipo==2
          @sactv_investigacion.push(@act)
        else
          if tipo==3
            @sactv_extension.push(@act)
          else
            if tipo==4
              @sactv_formacion.push(@act)
            else
              if tipo==5
                @sactv_otras.push(@act)
              end
            end
          end
        end
      end
    end

    @tactividadesa= AdecuacionActividad.where(adecuacion_id: @adecuacion.id, semestre: 3).all
    @tactividadesa.each do |actade| 
      @act= Actividad.find(actade.actividad_id)
      tipo= @act.tipo_actividad_id
      if tipo==1
        @tactv_docencia.push(@act)
      else
        if tipo==2
          @tactv_investigacion.push(@act)
        else
          if tipo==3
            @tactv_extension.push(@act)
          else
            if tipo==4
              @tactv_formacion.push(@act)
            else
              if tipo==5
                @tactv_otras.push(@act)
              end
            end
          end
        end
      end
    end

    @cactividadesa= AdecuacionActividad.where(adecuacion_id: @adecuacion.id, semestre: 4).all
    @cactividadesa.each do |actade| 
      @act= Actividad.find(actade.actividad_id)
      tipo= @act.tipo_actividad_id
      if tipo==1
        @cactv_docencia.push(@act)
      else
        if tipo==2
          @cactv_investigacion.push(@act)
        else
          if tipo==3
            @cactv_extension.push(@act)
          else
            if tipo==4
              @cactv_formacion.push(@act)
            else
              if tipo==5
                @cactv_otras.push(@act)
              end
            end
          end
        end
      end
    end

    @cactividadesa= AdecuacionActividad.where(adecuacion_id: @adecuacion.id, semestre: 5).all
    @cactividadesa.each do |actade| 
      @act= Actividad.find(actade.actividad_id)
      tipo= @act.tipo_actividad_id
      if tipo==1
        @dactv_docencia.push(@act)
      else
        if tipo==2
          @dactv_investigacion.push(@act)
        else
          if tipo==3
            @dactv_extension.push(@act)
          else
            if tipo==4
              @dactv_formacion.push(@act)
            end
          end
        end
      end
    end
    @documents = []
    @documents = Document.where(adecuacion_id: @adecuacion.id, informe_id: nil).all
    @numeroDeVersion = nil
    @actividades1 = []
    actividades = AdecuacionActividad.where(adecuacion_id: @adecuacion.id, semestre: 0)
    if !actividades.blank?
      actividades.each do |actividadAde|
        actividad = Actividad.find(actividadAde.actividad_id)
          @actividades1.push(actividad)
      end
    end
    # se llama a la función de "pedf_adecuacion" del modelo "pdf", pasando todas las variables correspondientes
    Pdf.pdf_adecuacion(@actividades1, @planformacion, @adecuacion, @tutor, @instructor, @correoi, @correot, @escuela, @pactv_docencia, @pactv_investigacion, @pactv_extension, @pactv_formacion, @pactv_otras, @sactv_docencia, @sactv_investigacion, @sactv_extension, @sactv_formacion, @sactv_otras, @tactv_docencia, @tactv_investigacion, @tactv_extension, @tactv_formacion, @tactv_otras, @cactv_docencia, @cactv_investigacion, @cactv_extension, @cactv_formacion, @cactv_otras, @fechaActual, @fechaConcurso, @documents, @numeroDeVersion, @dactv_docencia, @dactv_investigacion, @dactv_extension, @dactv_formacion)
    @nombre_archivo= @instructor.ci.to_s+'-'+@fechaActual+'-adecuacion.pdf' # se arma el nombre del documento 
    act = "#{Rails.root}/tmp/PDFs/" + @nombre_archivo
    #act = @nombre_archivo        #PRODUCCION
    send_file(
      act,
      filename: @nombre_archivo,
      type: "application/pdf"
    )
    return @nombre_archivo # se retorna el nombre del archivo
  end

####################################################################################  
  def descargar_pdf # esta función permite la generación y descarga del archivo PDF del documento
    require 'prawn'
    pdf = Prawn::Document.new
    pdf.text "Hello It's me"
    pdf.render_file "example.pdf"
    return "example.pdf"
    #pdf_filename = File.join(Rails.root, "example.pdf")
    #send_file(pdf_filename, :filename => "example.pdf", :disposition => 'inline', :type => "application/pdf")

  end

end

forminst_new1/app/helpers/adecuacions_helper.rb
module AdecuacionsHelper
end

forminst_new1/app/views/adecuacions/_form.html.erb
<%= form_for(@adecuacion) do |f| %>
  <% if @adecuacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adecuacion.errors.count, "error") %> prohibited this adecuacion from being saved:</h2>

      <ul>
      <% @adecuacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :PlanFormacionId %><br>
    <%= f.number_field :PlanFormacionId %>
  </div>
  <div class="field">
    <%= f.label :tutorId %><br>
    <%= f.number_field :tutorId %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

forminst_new1/app/views/adecuacions/descargar_pdf.html.erb
<iframe src="http://docs.google.com/gview?url=http://example.com/mypdf.pdf&embedded=true" style="width:718px; height:700px;" frameborder="0"></iframe>

forminst_new1/app/views/adecuacions/edit.html.erb
<h1>Editing Adecuacion</h1>

<%= render 'form' %>

<%= link_to 'Show', @adecuacion %> |
<%= link_to 'Back', adecuacions_path %>

forminst_new1/app/views/adecuacions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Adecuacions</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Planformacionid</th>
      <th>Tutorid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adecuacions.each do |adecuacion| %>
      <tr>
        <td><%= adecuacion.id %></td>
        <td><%= adecuacion.PlanFormacionId %></td>
        <td><%= adecuacion.tutorId %></td>
        <td><%= link_to 'Show', adecuacion %></td>
        <td><%= link_to 'Edit', edit_adecuacion_path(adecuacion) %></td>
        <td><%= link_to 'Destroy', adecuacion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adecuacion', new_adecuacion_path %>

forminst_new1/app/views/adecuacions/new.html.erb
<h1>New Adecuacion</h1>

<%= render 'form' %>

<%= link_to 'Back', adecuacions_path %>

forminst_new1/app/views/adecuacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @adecuacion.id %>
</p>

<p>
  <strong>Planformacionid:</strong>
  <%= @adecuacion.PlanFormacionId %>
</p>

<p>
  <strong>Tutorid:</strong>
  <%= @adecuacion.tutorId %>
</p>

<%= link_to 'Edit', edit_adecuacion_path(@adecuacion) %> |
<%= link_to 'Back', adecuacions_path %>