forminst_new1/config/routes.rb
Rails.application.routes.draw do
  resources :documents
	post 'iniciotutor/ver_detalles_plan', to: 'iniciotutor#ver_detalles_plan'
	get 'adecuacions/descargar_pdf', to: 'adecuacions#descargar_pdf'
	get ':controller(/:action(/:id(.:format)))'
	post ':controller(/:action(/:id(.:format)))'
	root 'forminst#index'

  resources :resumes, only: [:index, :new, :create, :destroy]
  root "resumes#index"

end

forminst_new1/app/models/document.rb
class Document < ActiveRecord::Base

  validate :file_size_under_one_mb
  validate :only_pdf

  def initialize(params = {})
    @file = params.delete(:file)
    super
    if @file
        self.filename = sanitize_filename(@file.original_filename)
        self.content_type = @file.content_type
        self.file_contents = @file.read
    end
  end

  private

    def sanitize_filename(filename)
      # Get only the filename, not the whole path (for IE)
      # Thanks to this article I just found for the tip: http://mattberther.com/2007/10/19/uploading-files-to-a-database-using-rails
      return File.basename(filename)
    end

    NUM_BYTES_IN_MEGABYTE = 1048576
    def file_size_under_one_mb
      if (@file.size.to_f / NUM_BYTES_IN_MEGABYTE) > 1
        errors.add(:file, 'El tamaño del archivo no puede ser mayor a 1 MB.')
      end
    end

    def only_pdf
      if (@file.content_type != "application/pdf")
        errors.add(:file, 'El archivo solo puede ser PDF')
      end
    end

end

forminst_new1/app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  layout 'ly_inicio_tutor'

  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    #pdf_filename = File.join(Rails.root, "tmp/PDFs/18810993-2017-07-02-adecuacion.pdf")
    #send_file(pdf_filename, :filename => "18810993-2017-07-02-adecuacion.pdf", :disposition => 'inline', :type => "application/pdf")
    #validar si se envio la adecuacion
      if session[:usuario_id] && session[:tutor]
        if(!session[:plan_id].blank?)

          @bool_enviado = 0
          @adecuacion = Adecuacion.where(planformacion_id: session[:plan_id]).take
          if session[:informe_id].blank?
            estatus_x = EstatusAdecuacion.where(adecuacion_id: @adecuacion.id, actual: 1).take
          else
            estatus_x = EstatusInforme.where(informe_id: session[:informe_id], actual: 1).take
          end
          if (estatus_x.estatus_id != 6 && estatus_x.estatus_id != 5)
            @bool_enviado = 1
          end
          @plan = Planformacion.where(id: session[:plan_id]).take

          if !@plan.blank?
            #Ver si el informe fue rachazado
            cpInstructor = Usuario.find(@plan.instructor_id)
            if (cpInstructor.activo == false)
              @cpBloquear = true
            else
              @cpBloquear = false
            end
            #fin
          end

          $actividad = params[:actividad_id].to_i
          @documents = []
          if !session[:informe_id].blank?
            @documents = Document.where("informe_id <= ? AND adecuacion_id = ? AND actividad_id = ?",session[:informe_id].to_i , session[:adecuacion_id],  $actividad).all
          else
            @documents = Document.where(adecuacion_id: session[:adecuacion_id], informe_id: nil).all
          end
        else
          flash.now[:info]="Seleccione una adecuación"
          redirect_to controller:"iniciotutor", action: "planformacions"
        end
      else
        redirect_to controller:"forminst", action: "index"
      end
  end

  # GET /documents/1.json
  def show
    puts "holaaaaaaaaaaaaaaaaaaaaaa"
    puts params[:commit]
    puts @document.filename
    send_data(@document.file_contents,
            type: @document.content_type,
            filename: @document.filename,
            disposition: 'inline')
  end

  # GET /documents/new
  def new
    @bool_enviado = 0
    if(!session[:plan_id].blank?)
      @adecuacion = Adecuacion.where(planformacion_id: session[:plan_id]).take
      if session[:informe_id].blank?
        estatus_x = EstatusAdecuacion.where(adecuacion_id: @adecuacion.id, actual: 1).take
      else
        estatus_x = EstatusInforme.where(informe_id: session[:informe_id], actual: 1).take
      end
      if (estatus_x.estatus_id != 6 && estatus_x.estatus_id != 5)
        @bool_enviado = 1
      end
      if ( @bool_enviado == 1)
        flash.now[:info]="No puede añadir soportes, ya ha enviado la adecuación"
      else
        @document = Document.new
      end
    else
      flash.now[:info]="Seleccione una adecuación"
      redirect_to controller:"iniciotutor", action: "planformacions"
    end
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    if session[:usuario_id] && session[:tutor]
	    if params[:document].present?
        @document = Document.new(document_params)
        @planformacion = Planformacion.find(session[:plan_id])
        @adecuacion = Adecuacion.where(planformacion_id: session[:plan_id]).take
        @document.instructor_id = @planformacion.instructor_id
        @document.tutor_id = session[:usuario_id]
        @document.adecuacion_id = @adecuacion.id
        @document.informe_id = session[:informe_id]
        @document.actividad_id = $actividad
        if @document.save
          flash[:success]="El documento se ha subido con exito"
          redirect_to controller:"documents", action: "index", :actividad_id => $actividad
        else
          flash[:danger]="Error: Recuerde que el documento debe ser un pdf que ocupe menos de 1MB"
          redirect_to controller:"documents", action: "new"
        end
      else
        flash[:info]="Debe seleccionar un archivo antes de cargar"
        redirect_to controller:"documents", action: "new"
      end
    else
      redirect_to controller:"forminst", action: "index"
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    flash[:success]="El documento fue borrado con exito"
    redirect_to controller:"documents", action: "index", :actividad_id => $actividad
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
     params.require(:document).permit(:file)
    end
end

forminst_new1/app/helpers/documents_helper.rb
module DocumentsHelper
end

forminst_new1/app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>

	<div class="row">
	    <div class="col-xs-5 col-md-5">  
	    	<div class="field">
	    		<%= f.file_field :file %>
	  		</div>
	  		<div class="actions">
				<%= f.submit "Subir Archivo", class: "btn btn-info" %>
			</div>
	  	</div>
	</div>
<% end %>

forminst_new1/app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

forminst_new1/app/views/documents/new.html.erb
<div class = 'row'>
  <div class="col-xs-12 col-md-12">
      <ul class="nav nav-tabs">
        <li><a href="../iniciotutor/index">Inicio</a></li>
        <%if session[:informe_id]%> 
	    	  <li><a href="../iniciotutor/planformacions">Plan de Formación</a></li>
  	    <%else %>
  	    	<li><a href="../iniciotutor/planformacions" class='active'>Plan de Formación</a></li>
  	    <%end%>
        <%if session[:informe_id]%> 
          <li class="dropdown">
	            <a href="#" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-expanded="false">Informes <span class="caret"></span></a>
	            <ul class="dropdown-menu nav" role="menu">
	              <li></li>
	              <li><a href="#" data-toggle="modal" data-target="#selectInforme">
	                Crear Informe
	              </a></li>
	              <li><%= link_to 'Listar Informes', :controller => 'informes', :action => 'listar_informes' %></li>
	            </ul>
	        </li>		
        <%else %>
  			<li class="dropdown">
  	            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Informes <span class="caret"></span></a>
  	            <ul class="dropdown-menu nav" role="menu">
  	              <li></li>
  	              <li><a href="#" data-toggle="modal" data-target="#selectInforme">
  	                Crear Informe
  	              </a></li>
  	              <li><%= link_to 'Listar Informes', :controller => 'informes', :action => 'listar_informes' %></li>
  	            </ul>
  	        </li>
		    <%end%>    
        <li><%= link_to 'Prórroga', :controller => 'iniciotutor', :action => 'prorroga' %></li>
        <li><a href="../iniciotutor/logout">Cerrar Sesión</a></li>
      </ul>
  </div>
</div>

<div class="modal fade" id="myModalEliminar1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h3 class="modal-title" id="myModalLabel">Eliminar Informe</h3>
      </div>
      <div class="modal-body">
        <h5>¿Está seguro que desea eliminar este informe?</h5>
      </div>
      <div class="modal-footer">
        <%= link_to "Aceptar", {controller: "informes", action: "eliminar_informe", :informe_id => session[:informe_id] }, class: "btn btn-default" %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModal1" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Mensaje de confirmación</h4>
      </div>
      <div class="modal-body">
        <h5>¿Está seguro que desea enviar el informe?</h5>
      </div>
      <div class="modal-footer">
        <%= link_to "Aceptar", {controller: "informes", action: "cambiar_estatusI", :informe_id => session[:informe_id] }, class: "btn btn-default" %>
      
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
      </div>
    </div>
    
  </div>
</div>

<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Mensaje de confirmación</h4>
      </div>
      <div class="modal-body">
      <center>
          <h5>¿Está seguro que desea enviar esta adecuación?</h5>
        </center>
      </div>
      <div class="modal-footer">
        <%= link_to "Aceptar", {controller: "iniciotutor", action: "cambiar_estatusA", :adecuacion_id => session[:adecuacion_id] }, class: "btn btn-default" %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
      </div>
    </div>
    
  </div>
</div>

<div class="modal fade" id="myModalEliminar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h3 class="modal-title" id="myModalLabel">Eliminar Adecuación</h3>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <center>
            <h5>¿Está seguro que desea eliminar esta adecuación?</h5>
          </center>
        </div>
      </div>
      <div class="modal-footer">
        <%= link_to "Aceptar", {controller: "iniciotutor", action: "eliminar_adecuacion" }, class: "btn btn-default" %>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModalEliminar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h3 class="modal-title" id="myModalLabel">Eliminar Adecuación</h3>
      </div>
      <div class="modal-body">
          <%= form_tag({controller: 'iniciotutor', action: 'eliminar_adecuacion'}) do%>
            <div class="form-group">
              <center>
                <h5>Está seguro que desea eliminar esta adecuación?</h5>
              </center>
            </div>
      </div>
      <div class="modal-footer">
          <button type="submit" class="btn btn-forminst">Si</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
      </div>
      <%end%>
    </div>
  </div>
</div>

<div class="modal fade" id="myModal2" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Mensaje de notificación</h4>
      </div>
      <div class="modal-body">
        <h5>El adecuación ya fue enviada.</h5>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Aceptar</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="selectInforme" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h3 class="modal-title" id="myModalLabel">Eliminar Informe</h3>
      </div>
      <div class="modal-body">
        <h5>Seleccione el informe a crear</h5>
      </div>
      <div class="modal-body">
        <b>&emsp;&emsp;&emsp;</b>
        <%= link_to "Informe 1", {controller: "informes", action: "ver_crear_informe", :informe_id => 1 }, class: "btn btn-forminst-blue" %>
        <b>&emsp;&emsp;&emsp;</b>
        <%= link_to "Informe 2", {controller: "informes", action: "ver_crear_informe", :informe_id => 2 }, class: "btn btn-forminst-blue" %>
        <b>&emsp;&emsp;&emsp;</b>
        <%= link_to "Informe 3", {controller: "informes", action: "ver_crear_informe", :informe_id => 3 }, class: "btn btn-forminst-blue" %>
        <b>&emsp;&emsp;&emsp;</b>
        <%= link_to "Informe 4", {controller: "informes", action: "ver_crear_informe", :informe_id => 4 }, class: "btn btn-forminst-blue" %>
        <p>   </p>
        <b>&emsp;&emsp;&emsp;</b>
        <%= link_to "Informe 5", {controller: "informes", action: "ver_crear_informe", :informe_id => 5 }, class: "btn btn-forminst-blue" %>
        <b>&emsp;&emsp;&emsp;</b>
        <%= link_to "Informe 6", {controller: "informes", action: "ver_crear_informe", :informe_id => 6 }, class: "btn btn-forminst-blue" %>
        <b>&emsp;&emsp;&emsp;</b>
        <%= link_to "Informe 7", {controller: "informes", action: "ver_crear_informe", :informe_id => 7 }, class: "btn btn-forminst-blue" %>
        <b>&emsp;&emsp;&emsp;</b>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-md-12">
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-default" onclick = " location.href = 'javascript:history.back(-1);'">Volver</button>
      <%if session[:informe_id]%> 
        <%= link_to "Volver al Informe", {controller: "informes", action: "detalles_informe2" }, class: "btn btn-default" %>
      <%else%> 
        <%= link_to "Volver a la Adecuación", {controller: "iniciotutor", action: "ver_detalles_adecuacion" }, class: "btn btn-default" %>
      <%end%> 
      <%if session[:informe_id]%> 
        <%= link_to "Vista Previa", {controller: "informes", action: "vista_previa"}, class: "btn btn-default" %>
      <%else%> 
		    <%= link_to "Vista Previa", {controller: "iniciotutor", action: "vista_previa"}, class: "btn btn-default" %>
      <%end%> 
      <%if session[:informe_id]%> 
        <%= link_to "Generar PDF", {controller: "informes", action: "generar_pdf"},target: :_blank, class: "btn btn-default" %>
      <%else%> 
        <%= link_to "Generar PDF", {controller: "adecuacions", action: "generar_pdf"},target: :_blank, class: "btn btn-default" %>
        <%= link_to "Agregar Soporte", {controller: "documents", action: "new"}, class: "btn btn-default active" %>
      <%end%> 
  		<%= link_to "Ver Soporte", {controller: "documents", action: "index", :actividad_id => $actividad }, class: "btn btn-default" %>
      <%if session[:informe_id]%> 
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModalEliminar1">Eliminar Informe</button>
      <%else %>
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModalEliminar">Eliminar Adecuación</button>
      <%end%>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 col-md-12 col-md-offset-0">
    <div class= "text-left">
      <%if session[:nombre_usuario]%>
        <div>
          <%if !session[:informe_id]%> 
            <span><%= link_to 'Plan Formación', :controller => 'iniciotutor', :action => 'planformacions' %></span>
            <p style="display:inline"> / </p>
            <span><%= link_to session[:instructorName] , :controller => 'iniciotutor', :action => 'ver_detalles_adecuacion' %></span>
            <p style="display:inline">  / Ver Soportes </p>
          <%else%> 
            <span><%= link_to 'Plan Formación', :controller => 'iniciotutor', :action => 'planformacions' %></span>
            <p style="display:inline"> / </p>
            <span><%= link_to session[:instructorName] , :controller => 'iniciotutor', :action => 'ver_detalles_adecuacion' %></span>
            <p style="display:inline"> / </p>
            <span><%= link_to 'Informes', :controller => 'informes', :action => 'listar_informes' %></span>
            <p style="display:inline">  / Ver Soportes </p>
          <%end%> 
        </div>
      <%end%>
    </div>
    <div class="text-right">
      <div id = "fechamuestra">
        <h3> <%= Time.now.strftime("%d") %>
          <% if Time.now.strftime("%m").to_i == 1 %>
            de Enero del
          <% elsif Time.now.strftime("%m").to_i == 2 %>
            de Febrero del
          <% elsif Time.now.strftime("%m").to_i == 3 %>
            de Marzo del
          <% elsif Time.now.strftime("%m").to_i == 4 %>
            de Abril del
          <% elsif Time.now.strftime("%m").to_i == 5 %>
            de Mayo del
          <% elsif Time.now.strftime("%m").to_i == 6 %>
            de Junio del
          <% elsif Time.now.strftime("%m").to_i == 7 %>
            de Julio del
          <% elsif Time.now.strftime("%m").to_i == 8 %>
            de Agosto del
          <% elsif Time.now.strftime("%m").to_i == 9 %>
            de Septiembre del
          <% elsif Time.now.strftime("%m").to_i == 10 %>
            de Octubre del
          <% elsif Time.now.strftime("%m").to_i == 11 %>
            de Noviembre del
          <% elsif Time.now.strftime("%m").to_i == 12 %>
            de Diciembre del
          <% end %>
          <%= Time.now.strftime("%Y") %> 
        </h3>
      </div>
      <%if session[:nombre_usuario]%>
        <div>
          <h4><b><%=session[:nombre_usuario]%></b></h4>
        </div>
      <%end%>
    </div>
  </div>
</div>

<h1>Cargar Documento</h1>
<h4 >El archivo a adjuntar debe tener un tamaño menor a 1 MB </h4><br></br>
<br></br>
<%if @bool_enviado == 0%>
  <%= render 'form', document: @document %>
<%else%>
  <div class= "text-center">
  <h4 >No puede agregar más soportes</h4><br></br>
  </div>
<%end%>
<br></br>

<br></br>

forminst_new1/app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @document.filename %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @document.content_type %>
</p>

<p>
  <strong>File contents:</strong>
  <%= @document.file_contents %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>